### ISSUE TITLE
Needs a 64x64 and 128x128 icon

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.gnome.Weather#2]
In order to show up on the [apps page](https://beta.flathub.org/apps) this needs to have 64x64 and 128x128px icons. However this app only has 48x48 and then a gap until 256x256px:

https://git.gnome.org/browse/gnome-weather/tree/data/icons/hicolor

@jgarciao this also has an SVG icon, not sure if that could be useful as a fallback as well.

**Comment by gcampax** [comment]
The flatpak includes whatever the upstream app includes.
Could you file a bug in the GNOME Bugzilla, where the other app issues are tracked?

Thanks!

**Comment by nedrichards** [comment]
Yup, for sure. https://bugzilla.gnome.org/show_bug.cgi?id=792573

**Comment by BrainBlasted** [comment]
Is this still valid? Apps are moving toward shipping only scalable icons for 3.32.

**Comment by jgarciao** [comment]
I asked flathub-admins and got this answer from @ramcq:

- We require 64x64 and 128x128 in the Flathub requirements, because appstream-compose is only looking for these sizes from the icon specified by the .desktop file
https://github.com/hughsie/appstream-glib/blob/master/client/as-compose.c#L53

- Some apps add code into the manifest to generate icons at different sizes using the svg file: 
https://github.com/search?q=org%3Aflathub+rsvg-convert&type=Code

**Comment by bilelmoussaoui** [comment]
I think we can close this
